env = Environment()
env.Append(
  CXXFLAGS = [
    '-std=gnu++11'
  ],
  LIBS = [
    'gtest',
    'gtest_main',
    'boost_filesystem',
    "boost_system",
    'pthread'
])

env.Program('unit_test', Glob('*.cpp'))
